development:
  redis:
    host: localhost
    port: 6379
  fluent:
    host: '127.0.0.1'
    port: 24224
    appname: debug

test:
  redis:
    host: localhost
    port: 6379
  fluent:
    host: '127.0.0.1'
    port: 24224
    appname: debug


production:
  redis:
    host: localhost
    port: 6379
  fluent:
    host: '127.0.0.1'
    port: 24224
    appname: debug