development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rackrest_development
  pool: 25
  host: localhost
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rackrest_test
  pool: 25
  host: localhost
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rackrest_development
  pool: 25
  host: localhost
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock